services:
  app:
    build: .
    container_name: zyeta-backend
    env_file: .env
    ports:
      - "8001:8000"
    networks:
      - app_network
    restart: unless-stopped
    # Add DNS settings to help with external connections
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Add healthcheck for the app
    healthcheck:
      test: ["CMD", "curl", "-f", "https://api.myip.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app_network:
    driver: bridge