name: Deploy to Server on Dev Push

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.dev.SERVER_HOST }}
          username: ${{ secrets.dev.SERVER_USER }}
          key: ${{ secrets.dev.SERVER_SSH_KEY }}
          port: ${{ secrets.dev.SERVER_PORT }}
          script: |
            cd /root/app_services/zyeta.backend 
            git pull
            docker compose up --build -d
